# Databricks Schema: depss-poc-schema-187
# Generated by Toyota Data Engineering Portal
# Environment: dev
# Owner: nravikirankumar@gmail.com

terraform {
  required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = "~> 1.0"
    }
  }
}

resource "databricks_schema" "depss_poc_schema_187" {
  catalog_name = "depss-poc-catlog"
  name         = "depss-poc-schema-187"
  comment      = "Schema for my-customer-app application"
  owner        = "nravikirankumar@gmail.com"

  properties = {
    environment = "dev"
    managed_by  = "Terraform"
    created_by  = "Toyota-Data-Engineering-Portal"
  }
}

output "depss_poc_schema_187_full_name" {
  value       = databricks_schema.depss_poc_schema_187.id
  description = "The full name of the schema (catalog.schema)"
}
